### PR TITLE
[GetEmoji] Add typing

### PR DESCRIPTION
**Pull request by OofChair**
this should work iirc, but let me test first <:aha:350653489044652052>

### CODE REVIEW

**Comment by OofChair** [comment]
Tested, should be good to merge :p

**Comment by Ryan5453** [comment]
thanks 4 the pr :squirt:

**Comment by OofChair** [comment]
NO :beating:

**Comment by Ryan5453** [comment]
:tied:

**Comment by Ryan5453** [comment]
<:headjob:816109524917682206> <:headjob:816109524917682206> <:headjob:816109524917682206> <:headjob:816109524917682206> <:headjob:816109524917682206>

**Comment by OofChair** [comment]
STOP

**Pull request merged**
